services:
  # Base de Datos
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pedidos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # API Backend
  backend:
    build: ./backend
    ports:
      - "4000:3000" # Acceso local en puerto 4000
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password123
      DB_NAME: pedidos_db
      DB_PORT: 5432
      NODE_ENV: development
    depends_on:
      - db
    volumes: 
      - ./backend:/app
      - /app/node_modules
    command: npm run dev


  # App Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Acceso local en puerto 3000
    stdin_open: true # Necesario para React en Docker
    tty: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - BROWSER=none
      - HOST=0.0.0.0
      - PORT=3000
      - WDS_SOCKET_HOST=0.0.0.0
      - WDS_SOCKET_PORT=3000
      - WDS_SOCKET_PATH=/sockjs-node
      - WDS_SOCKET_URL=ws://0.0.0.0:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: