
-- No es necesario crear la base de datos con este script,
-- Docker Compose se encarga de ello usando las variables de entorno.

-- Usamos "users" en lugar de "user" porque "user" es una palabra reservada en PostgreSQL.
-- También se corrigió un error de sintaxis (una coma al final).
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

-- Tabla para el menú del restaurante
CREATE TABLE menus (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    descripcion TEXT,
    precio DECIMAL(10, 2) NOT NULL,
    visible BOOLEAN DEFAULT true
);

-- Insertar usuario admin
INSERT INTO users (email, password)
VALUES ('admin@pedidiosahora.com', 'password123');


INSERT INTO menus (nombre, descripcion, precio, visible) VALUES
('Menú Obrero', 'Plato: Milanesa de ternera. Guarnición: Papas fritas. Bebida: Soda sifón. Postre: Flan con dulce de leche.', 12.00, true),
('Menú Domingo', 'Plato: Asado de tira. Guarnición: Ensalada mixta. Bebida: Vino tinto. Postre: Helado de dulce de leche.', 16.50, true),
('Menú de Bodegón', 'Plato: Suprema de pollo napolitana. Guarnición: Papas rejilla. Bebida: Gaseosa. Postre: Budín de pan mixto.', 13.50, true),
('Menú Bodegón I', 'Plato: Ravioles de seso y espinaca. Guarnición: Estofado de carne. Bebida: Agua con gas. Postre: Queso y dulce de batata.', 12.50, true),
('Menú del Puerto', 'Plato: Pejerrey a la romana. Guarnición: Puré de papas. Bebida: Vino blanco. Postre: Ensalada de frutas.', 14.00, true),
('Menú Parrillero', 'Plato: Vacío a la parrilla. Guarnición: Papas al plomo con crema. Bebida: Vino tinto. Postre: Panqueque con dulce de leche.', 17.00, true),
('Menú Minuta Clásica', 'Plato: Churrasco de lomo. Guarnición: Ensalada de rabanitos y lechuga. Bebida: Cerveza quilmes. Postre: Peras al malbec.', 15.00, true),
('Menú de Invierno', 'Plato: Locro criollo. Guarnición: Pan casero. Bebida: Vino tinto de la casa. Postre: Arroz con leche.', 11.50, true),
('Menú Noroeste', 'Plato: Humita en olla. Guarnición: Empanada de carne cortada a cuchillo. Bebida: Vino torrontés. Postre: Dulce de cayote con nuez.', 13.00, true),
('Menú de la Nonna', 'Plato: Ñoquis de papa. Guarnición: Salsa bolognesa casera. Bebida: Agua mineral. Postre: Tiramisú de vainillas.', 11.00, true),
('Menú Campero', 'Plato: Matambre a la pizza. Guarnición: Papas fritas a caballo. Bebida: Cerveza. Postre: Vigilante (Queso y membrillo).', 14.50, true),
('Menú Del Barrio', 'Plato: Tortilla de papas española. Guarnición: Ensalada de tomate y cebolla. Bebida: Soda. Postre: Mousse de chocolate.', 10.50, true),
('Menú Ejecutivo I', 'Plato: Bife de cuadril. Guarnición: Puré mixto. Bebida: Paso de los Toros. Postre: Manzana asada.', 13.50, true),
('Menú Patagónico', 'Plato: Cordero al horno. Guarnición: Papas rústicas. Bebida: Vino pinot noir. Postre: Frutos rojos con crema.', 19.00, true),
('Menú Tradicional', 'Plato: Carbonada criolla. Guarnición: Arroz blanco. Bebida: Agua. Postre: Mazamorra.', 12.00, true),
('Menú de Lujo', 'Plato: Entraña con chimichurri. Guarnición: Verduras asadas. Bebida: Vino malbec. Postre: Volcán de dulce de leche.', 18.50, true),
('Menú Rápido', 'Plato: Choripán de campo. Guarnición: Papas fritas. Bebida: Fernet con cola. Postre: Alfajor regional.', 9.50, true),
('Menú de Campo I', 'Plato: Pollo al disco. Guarnición: Pan de campo. Bebida: Vino tinto. Postre: Zapallos en almíbar.', 14.00, true),
('Menú Marino', 'Plato: Merluza a la plancha. Guarnición: Acelga con blanca. Bebida: Agua con limón. Postre: Gelatina con frutas.', 11.00, true),
('Menú Porteño II', 'Plato: Canelones de ricota y nuez. Guarnición: Salsa tuco. Bebida: Copa de vino. Postre: Chocoflan.', 12.50, true),
('Menú Estanciero', 'Plato: Ojo de bife. Guarnición: Papas pay. Bebida: Agua mineral. Postre: Don Pedro (Helado y whisky).', 18.00, true),
('Menú Litoral', 'Plato: Pacú a las brasas. Guarnición: Mandioca frita. Bebida: Cerveza rubia. Postre: Papaya en almíbar.', 15.50, true),
('Menú de Otoño', 'Plato: Guiso de lentejas. Guarnición: Panceta y chorizo colorado. Bebida: Vino tinto. Postre: Pastelito de membrillo.', 11.00, true),
('Menú Minuta II', 'Plato: Milanesa de pollo. Guarnición: Puré de calabaza. Bebida: Jugo natural. Postre: Yogur con cereales.', 11.00, true),
('Menú Cantina', 'Plato: Fusilli al fierrito. Guarnición: Salsa pesto y nueces. Bebida: Soda. Postre: Chocotorta.', 13.00, true),
('Menú Picnic', 'Plato: Sandwich de milanesa completo. Guarnición: Papas fritas. Bebida: Coca-Cola. Postre: Bombón suizo.', 10.00, true),
('Menú Criollo', 'Plato: Lengua a la vinagreta. Guarnición: Ensalada rusa. Bebida: Vermut con soda. Postre: Flan con crema.', 12.00, true),
('Menú Regional', 'Plato: Tamales salteños. Guarnición: Empanada tucumana. Bebida: Vino patero. Postre: Quesillo con miel de caña.', 13.50, true),
('Menú de Estación', 'Plato: Zapallitos rellenos. Guarnición: Arroz primavera. Bebida: Agua saborizada. Postre: Duraznos en almíbar.', 10.00, true),
('Menú Carnicero', 'Plato: Colita de cuadril al horno. Guarnición: Papas y batatas. Bebida: Vino tinto. Postre: Postre Balcarce.', 15.00, true),
('Menú Mar del Plata', 'Plato: Calamares rellenos. Guarnición: Arroz con azafrán. Bebida: Vino blanco. Postre: Alfajor marplatense.', 16.00, true),
('Menú Saludable', 'Plato: Pechuga de pollo grillada. Guarnición: Ensalada de rúcula y parmesano. Bebida: Té helado. Postre: Ensalada de frutas.', 12.00, true),
('Menú Nostalgia', 'Plato: Polenta con pajaritos (estofado). Guarnición: Queso muzzarella. Bebida: Vino tinto. Postre: Torta frita con azúcar.', 10.50, true),
('Menú de Quinta', 'Plato: Conejo a la cazadora. Guarnición: Papas noisette. Bebida: Vino blanco. Postre: Higos en almíbar.', 17.50, true),
('Menú Urbano', 'Plato: Bondiola de cerdo al horno. Guarnición: Puré de batatas con miel. Bebida: Cerveza artesanal. Postre: Brownie con helado.', 14.50, true),
('Menú Caserito', 'Plato: Albóndigas con puré. Guarnición: Salsa de tomate. Bebida: Jugo de naranja. Postre: Gelatina.', 10.00, true),
('Menú de Parrilla II', 'Plato: Chinchulines y riñones grillados. Guarnición: Ensalada criolla. Bebida: Cerveza. Postre: Panqueque de manzana quemado al rhum.', 14.00, true),
('Menú Elegante', 'Plato: Lomo a la pimienta. Guarnición: Papas a la crema. Bebida: Vino Malbec reserva. Postre: Sambayón con nueces.', 20.00, true),
('Menú Ferroviario', 'Plato: Tallarines con estofado de pollo. Guarnición: Queso rallado. Bebida: Soda sifón. Postre: Queso y dulce de membrillo.', 11.50, true),
('Menú de Mesón', 'Plato: Mondongo a la española. Guarnición: Porotos de garbanzo. Bebida: Vino tinto. Postre: Natilla.', 12.50, true),
('Menú de Viernes', 'Plato: Pizza de molde muzzarella. Guarnición: Fainá con orégano. Bebida: Cerveza tirada. Postre: Helado de chocolate.', 11.00, true),
('Menú Serrano', 'Plato: Cabrito al horno. Guarnición: Papas fritas. Bebida: Vino tinto cordobés. Postre: Alfajor de maicena.', 18.00, true),
('Menú Festivo', 'Plato: Vitel Toné. Guarnición: Ensalada de papa y huevo. Bebida: Ananá Fizz o Gaseosa. Postre: Pan dulce.', 15.00, true),
('Menú Liviano', 'Plato: Tarta de zapallitos. Guarnición: Ensalada de zanahoria rallada. Bebida: Agua. Postre: Manzana roja.', 9.50, true),
('Menú Gourmet Argento', 'Plato: Risotto de hongos de pino. Guarnición: Ensalada de brotes. Bebida: Copa de Chardonnay. Postre: Degustación de dulces regionales.', 16.00, true),
('Menú Obrero II', 'Plato: Sándwich de vacío. Guarnición: Papas fritas con provenzal. Bebida: Gaseosa de litro compartida. Postre: Helado de palito.', 11.00, true),
('Menú Mendocino', 'Plato: Tomaticán (Guiso de tomate y huevo). Guarnición: Tortitas mendocinas. Bebida: Vino Malbec. Postre: Alcayota.', 12.00, true),
('Menú Nocturno', 'Plato: Sorrentinos de calabaza. Guarnición: Salsa blanca y nuez. Bebida: Vino blanco dulce. Postre: Mousse de limón.', 13.00, true),
('Menú de Bodega', 'Plato: Empanadas de carne y queso. Guarnición: Tabla de fiambres. Bebida: Degustación de vinos. Postre: Bombón escocés.', 17.00, true),
('Menú Final', 'Plato: Milanesa de ternera completa (huevo frito). Guarnición: Papas fritas y ensalada. Bebida: Coca-Cola original. Postre: Copa de la casa (Helado, frutas y crema).', 14.50, true);
('Menú Obrero', 'Plato: Milanesa de ternera. Guarnición: Papas fritas. Bebida: Soda sifón. Postre: Flan con dulce de leche.', 12000.00, true),
('Menú Domingo', 'Plato: Asado de tira. Guarnición: Ensalada mixta. Bebida: Vino tinto. Postre: Helado de dulce de leche.', 16500.00, true),
('Menú de Bodegón', 'Plato: Suprema de pollo napolitana. Guarnición: Papas rejilla. Bebida: Gaseosa. Postre: Budín de pan mixto.', 13500.00, true),
('Menú Bodegón I', 'Plato: Ravioles de seso y espinaca. Guarnición: Estofado de carne. Bebida: Agua con gas. Postre: Queso y dulce de batata.', 12500.00, true),
('Menú del Puerto', 'Plato: Pejerrey a la romana. Guarnición: Puré de papas. Bebida: Vino blanco. Postre: Ensalada de frutas.', 14000.00, true),
('Menú Parrillero', 'Plato: Vacío a la parrilla. Guarnición: Papas al plomo con crema. Bebida: Vino tinto. Postre: Panqueque con dulce de leche.', 17000.00, true),
('Menú Minuta Clásica', 'Plato: Churrasco de lomo. Guarnición: Ensalada de rabanitos y lechuga. Bebida: Cerveza quilmes. Postre: Peras al malbec.', 15000.00, true),
('Menú de Invierno', 'Plato: Locro criollo. Guarnición: Pan casero. Bebida: Vino tinto de la casa. Postre: Arroz con leche.', 11500.00, true),
('Menú Noroeste', 'Plato: Humita en olla. Guarnición: Empanada de carne cortada a cuchillo. Bebida: Vino torrontés. Postre: Dulce de cayote con nuez.', 13000.00, true),
('Menú de la Nonna', 'Plato: Ñoquis de papa. Guarnición: Salsa bolognesa casera. Bebida: Agua mineral. Postre: Tiramisú de vainillas.', 11000.00, true),
('Menú Campero', 'Plato: Matambre a la pizza. Guarnición: Papas fritas a caballo. Bebida: Cerveza. Postre: Vigilante (Queso y membrillo).', 14500.00, true),
('Menú Del Barrio', 'Plato: Tortilla de papas española. Guarnición: Ensalada de tomate y cebolla. Bebida: Soda. Postre: Mousse de chocolate.', 10500.00, true),
('Menú Ejecutivo I', 'Plato: Bife de cuadril. Guarnición: Puré mixto. Bebida: Paso de los Toros. Postre: Manzana asada.', 13500.00, true),
('Menú Patagónico', 'Plato: Cordero al horno. Guarnición: Papas rústicas. Bebida: Vino pinot noir. Postre: Frutos rojos con crema.', 19000.00, true),
('Menú Tradicional', 'Plato: Carbonada criolla. Guarnición: Arroz blanco. Bebida: Agua. Postre: Mazamorra.', 12000.00, true),
('Menú de Lujo', 'Plato: Entraña con chimichurri. Guarnición: Verduras asadas. Bebida: Vino malbec. Postre: Volcán de dulce de leche.', 18500.00, true),
('Menú Rápido', 'Plato: Choripán de campo. Guarnición: Papas fritas. Bebida: Fernet con cola. Postre: Alfajor regional.', 9500.00, true),
('Menú de Campo I', 'Plato: Pollo al disco. Guarnición: Pan de campo. Bebida: Vino tinto. Postre: Zapallos en almíbar.', 14000.00, true),
('Menú Marino', 'Plato: Merluza a la plancha. Guarnición: Acelga con blanca. Bebida: Agua con limón. Postre: Gelatina con frutas.', 11000.00, true),
('Menú Porteño II', 'Plato: Canelones de ricota y nuez. Guarnición: Salsa tuco. Bebida: Copa de vino. Postre: Chocoflan.', 12500.00, true),
('Menú Estanciero', 'Plato: Ojo de bife. Guarnición: Papas pay. Bebida: Agua mineral. Postre: Don Pedro (Helado y whisky).', 18000.00, true),
('Menú Litoral', 'Plato: Pacú a las brasas. Guarnición: Mandioca frita. Bebida: Cerveza rubia. Postre: Papaya en almíbar.', 15500.00, true),
('Menú de Otoño', 'Plato: Guiso de lentejas. Guarnición: Panceta y chorizo colorado. Bebida: Vino tinto. Postre: Pastelito de membrillo.', 11000.00, true),
('Menú Minuta II', 'Plato: Milanesa de pollo. Guarnición: Puré de calabaza. Bebida: Jugo natural. Postre: Yogur con cereales.', 11000.00, true),
('Menú Cantina', 'Plato: Fusilli al fierrito. Guarnición: Salsa pesto y nueces. Bebida: Soda. Postre: Chocotorta.', 13000.00, true),
('Menú Picnic', 'Plato: Sandwich de milanesa completo. Guarnición: Papas fritas. Bebida: Coca-Cola. Postre: Bombón suizo.', 10000.00, true),
('Menú Criollo', 'Plato: Lengua a la vinagreta. Guarnición: Ensalada rusa. Bebida: Vermut con soda. Postre: Flan con crema.', 12000.00, true),
('Menú Regional', 'Plato: Tamales salteños. Guarnición: Empanada tucumana. Bebida: Vino patero. Postre: Quesillo con miel de caña.', 13500.00, true),
('Menú de Estación', 'Plato: Zapallitos rellenos. Guarnición: Arroz primavera. Bebida: Agua saborizada. Postre: Duraznos en almíbar.', 10000.00, true),
('Menú Carnicero', 'Plato: Colita de cuadril al horno. Guarnición: Papas y batatas. Bebida: Vino tinto. Postre: Postre Balcarce.', 15000.00, true),
('Menú Mar del Plata', 'Plato: Calamares rellenos. Guarnición: Arroz con azafrán. Bebida: Vino blanco. Postre: Alfajor marplatense.', 16000.00, true),
('Menú Saludable', 'Plato: Pechuga de pollo grillada. Guarnición: Ensalada de rúcula y parmesano. Bebida: Té helado. Postre: Ensalada de frutas.', 12000.00, true),
('Menú Nostalgia', 'Plato: Polenta con pajaritos (estofado). Guarnición: Queso muzzarella. Bebida: Vino tinto. Postre: Torta frita con azúcar.', 10500.00, true),
('Menú de Quinta', 'Plato: Conejo a la cazadora. Guarnición: Papas noisette. Bebida: Vino blanco. Postre: Higos en almíbar.', 17500.00, true),
('Menú Urbano', 'Plato: Bondiola de cerdo al horno. Guarnición: Puré de batatas con miel. Bebida: Cerveza artesanal. Postre: Brownie con helado.', 14500.00, true),
('Menú Caserito', 'Plato: Albóndigas con puré. Guarnición: Salsa de tomate. Bebida: Jugo de naranja. Postre: Gelatina.', 10000.00, true),
('Menú de Parrilla II', 'Plato: Chinchulines y riñones grillados. Guarnición: Ensalada criolla. Bebida: Cerveza. Postre: Panqueque de manzana quemado al rhum.', 14000.00, true),
('Menú Elegante', 'Plato: Lomo a la pimienta. Guarnición: Papas a la crema. Bebida: Vino Malbec reserva. Postre: Sambayón con nueces.', 20000.00, true),
('Menú Ferroviario', 'Plato: Tallarines con estofado de pollo. Guarnición: Queso rallado. Bebida: Soda sifón. Postre: Queso y dulce de membrillo.', 11500.00, true),
('Menú de Mesón', 'Plato: Mondongo a la española. Guarnición: Porotos de garbanzo. Bebida: Vino tinto. Postre: Natilla.', 12500.00, true),
('Menú de Viernes', 'Plato: Pizza de molde muzzarella. Guarnición: Fainá con orégano. Bebida: Cerveza tirada. Postre: Helado de chocolate.', 11000.00, true),
('Menú Serrano', 'Plato: Cabrito al horno. Guarnición: Papas fritas. Bebida: Vino tinto cordobés. Postre: Alfajor de maicena.', 18000.00, true),
('Menú Festivo', 'Plato: Vitel Toné. Guarnición: Ensalada de papa y huevo. Bebida: Ananá Fizz o Gaseosa. Postre: Pan dulce.', 15000.00, true),
('Menú Liviano', 'Plato: Tarta de zapallitos. Guarnición: Ensalada de zanahoria rallada. Bebida: Agua. Postre: Manzana roja.', 9500.00, true),
('Menú Gourmet Argento', 'Plato: Risotto de hongos de pino. Guarnición: Ensalada de brotes. Bebida: Copa de Chardonnay. Postre: Degustación de dulces regionales.', 16000.00, true),
('Menú Obrero II', 'Plato: Sándwich de vacío. Guarnición: Papas fritas con provenzal. Bebida: Gaseosa de litro compartida. Postre: Helado de palito.', 11000.00, true),
('Menú Mendocino', 'Plato: Tomaticán (Guiso de tomate y huevo). Guarnición: Tortitas mendocinas. Bebida: Vino Malbec. Postre: Alcayota.', 12000.00, true),
('Menú Nocturno', 'Plato: Sorrentinos de calabaza. Guarnición: Salsa blanca y nuez. Bebida: Vino blanco dulce. Postre: Mousse de limón.', 13000.00, true),
('Menú de Bodega', 'Plato: Empanadas de carne y queso. Guarnición: Tabla de fiambres. Bebida: Degustación de vinos. Postre: Bombón escocés.', 17000.00, true),
('Menú Final', 'Plato: Milanesa de ternera completa (huevo frito). Guarnición: Papas fritas y ensalada. Bebida: Coca-Cola original. Postre: Copa de la casa (Helado, frutas y crema).', 14500.00, true);